### ISSUE TITLE
Report per-cell clone assignments?

### ISSUE THREAD

**Issue by murphycj** [cbg-ethz/COMPASS#1]
Hello! 

Really interesting tool. Basic question, but does COMPASS output a file containing the per-cell clone assignments as well as the genotypes in each clone? I ask because that would make it easier to programmatically use the data for other downstream tasks.

Thanks!

**Comment by e-sollier** [comment]
Hi,

Thanks for your interest in COMPASS!
COMPASS used to only output the tree in graphviz format, but I have just added other outputs, including assignments of cells to nodes and genotypes of nodes. The outputs are now described in the readme, and you can see an example of an output generated by COMPASS in https://github.com/cbg-ethz/COMPASS/tree/master/data/output . 
I hope this helps, and I'd be happy to help if you have further questions.

Cheers,
Etienne

**Comment by murphycj** [comment]
That is exactly what I wanted, thank you!

One small question. I see in your `_cellAssignments.tsv` example file that the node assignments for one cell is `25`, which is not listed in the `_genotypes.tsv` file. I presume that node is a doublet, which is listed in the `_cellAssignmentsProbs.tsv` file?

Example: [https://github.com/cbg-ethz/COMPASS/blob/master/data/output/AML-59-001_cellAssignments.tsv#L318](https://github.com/cbg-ethz/COMPASS/blob/master/data/output/AML-59-001_cellAssignments.tsv#L318)

**Comment by murphycj** [comment]
Thanks for the clarification and update. I think the changes you made are sufficient. Right now I cannot think of a reason to need the full doublet information.
