### ISSUE TITLE
Compilation on M3 processors

### ISSUE THREAD

**Issue by andreyurch** [cbg-ethz/COMPASS#15]
Dear developers, 
Is it possible to run the tool on M3 MacBook? I have tried to compile, but was not successful.

**Comment by e-sollier** [comment]
I don't have a mac computer to test, but there is no reason why COMPASS should not run on macOS. Just make sure that you have a C++ compiler installed, and potentially change the first line of the Makefile to match your compiler (e.g. CXX = clang++). If this does not work, could you please copy the error message that you get ?

**Comment by kjpg** [comment]
I am going to hijack this issue.  I get the same.  I get an fopenmp error plus a permission error.  

```
(compass_env) griffink2@awld3094kg COMPASS % make             
./COMPASS -i data/preprocessed_data_AML_Morita2020/AML-59-001 -o AML-59-001 --nchains 4 --chainlength 5000 --CNA 1
dot -Tpng -o AML-59-001_tree.png
g++ -std=c++11 -O2 -fopenmp -c COMPASS.cpp
clang: error: unsupported option '-fopenmp'
make: *** [COMPASS.o] Error 1
zsh: permission denied: ./COMPASS
```

1. permissions: I didn't have rwx access but I changed it (chmod 755) to all files in COMPASS/.  But I still get the permission error

<img width="456" alt="Screenshot 2024-06-05 at 4 21 28 PM" src="https://github.com/cbg-ethz/COMPASS/assets/5115786/19493024-6742-4e92-8e1a-5309076dd68d">







2.**fopenmp**.
apparently this is a common issue, with the Apple clang. 

 I did the simple change (clang++), which didn't help.  Googling, I installed using homebrew and added that directory path  to Makefile 

```
CXX	= /opt/homebrew/Cellar/gcc/14.1.0_1/bin/aarch64-apple-darwin23-g++-14
CXXFLAGS = -std=c++11 -O2
```

and now I see this, which is something of an improvement but not a total fix

```
(compass_env) griffink2@awld3094kg COMPASS % make         
./COMPASS -i data/preprocessed_data_AML_Morita2020/AML-59-001 -o AML-59-001 --nchains 4 --chainlength 5000 --CNA 1
dot -Tpng -o AML-59-001_tree.png
/opt/homebrew/Cellar/gcc/14.1.0_1/bin/aarch64-apple-darwin23-g++-14 -std=c++11 -O2 -fopenmp -c COMPASS.cpp
/opt/homebrew/Cellar/gcc/14.1.0_1/bin/aarch64-apple-darwin23-g++-14 -std=c++11 -O2 -c Scores.cpp
/opt/homebrew/Cellar/gcc/14.1.0_1/bin/aarch64-apple-darwin23-g++-14 -std=c++11 -O2 -c Node.cpp
/opt/homebrew/Cellar/gcc/14.1.0_1/bin/aarch64-apple-darwin23-g++-14 -std=c++11 -O2 -c Tree.cpp
/opt/homebrew/Cellar/gcc/14.1.0_1/bin/aarch64-apple-darwin23-g++-14 -std=c++11 -O2 -c Inference.cpp
/opt/homebrew/Cellar/gcc/14.1.0_1/bin/aarch64-apple-darwin23-g++-14 -std=c++11 -O2 -c input.cpp 
/opt/homebrew/Cellar/gcc/14.1.0_1/bin/aarch64-apple-darwin23-g++-14 -std=c++11 -O2 -fopenmp -o COMPASS COMPASS.o Scores.o Node.o Tree.o Inference.o input.o
ld: open() failed, errno=21 for 'COMPASS'
collect2: error: ld returned 1 exit status
make: *** [COMPASS] Error 1
zsh: permission denied: ./COMPASS
```

Any ideas?

Christine

**Comment by kjpg** [comment]
btw, I am not really a coder

**Comment by e-sollier** [comment]
Hello,

Thanks for the report. Can you try the answer provided here https://stackoverflow.com/questions/39979836/using-openmp-with-c11-on-mac-os :
1. Run `brew install libomp`
2. In the makefile, add `-Xpreprocessor` next to `-fopenmp`, so the makefile should look like:

```
CXX	= clang++
CXXFLAGS = -std=c++11 -O2


COMPASS: COMPASS.o Scores.o Node.o Tree.o Inference.o input.o
	${CXX} ${CXXFLAGS} -Xpreprocessor -fopenmp -o COMPASS COMPASS.o Scores.o Node.o Tree.o Inference.o input.o


COMPASS.o: COMPASS.cpp Inference.h Tree.h input.h Scores.h Structures.h
	${CXX} ${CXXFLAGS} -Xpreprocessor -fopenmp -c COMPASS.cpp
Scores.o: Scores.cpp Scores.h Structures.h
	${CXX} ${CXXFLAGS} -c Scores.cpp
Node.o:  Node.cpp Node.h Scores.h Structures.h
	${CXX} ${CXXFLAGS} -c Node.cpp
Tree.o: Tree.cpp Tree.h Node.h Scores.h Structures.h input.h
	${CXX} ${CXXFLAGS} -c Tree.cpp
Inference.o: Inference.cpp Inference.h Structures.h Scores.h Tree.h
	${CXX} ${CXXFLAGS} -c Inference.cpp
input.o: input.cpp input.h Structures.h Scores.h
	${CXX} ${CXXFLAGS} -c input.cpp 
clean:
	rm *.o
```

Does this fix your compilation error?

**Comment by RaphaelHablesreiter** [comment]
Hi,
you can run `conda install compilers llvm-openmp` and then comment CXX and CXXFLAGS out.
Maybe that helps!

**Comment by kjpg** [comment]
By the way, I have also been tgrying to install Mosaic, also errorprone.  Contacted MissionBio, who sent updated links but also said it now incorporates COMPASS.  Is this news to you? Should I still try to fix this COMPASS install?  

In the meantime,  the clang change generated a very long output, whcih may be normal verbose actual run, flanked with errors (see below). (
I'll try the conda suggestion next)

started 
```

clang++ -std=c++11 -O2 -Xpreprocessor -fopenmp -o COMPASS COMPASS.o Scores.o Node.o Tree.o Inference.o input.o
Undefined symbols for architecture arm64:
  "_GOMP_parallel", referenced from:
      _main in COMPASS.o
  "std::__basic_file<char>::is_open() const", referenced from:
      load_CSV(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>, bool) in input.o

```

ending

 ```
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "_omp_get_num_procs", referenced from:
      _main in COMPASS.o
      _main in COMPASS.o
  "_omp_get_num_threads", referenced from:
      _main._omp_fn.0 in COMPASS.o
  "_omp_get_thread_num", referenced from:
      _main._omp_fn.0 in COMPASS.o
  "_omp_set_num_threads", referenced from:
      _main in COMPASS.o
      _main in COMPASS.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [COMPASS] Error 1
zsh: permission denied: ./COMPASS
Error: dot: can't open AML-59-001_tree.gv: No such file or directory
```

**Comment by kjpg** [comment]
no joy. "package not available" from compilers.  told me to search anaconda.org. I tried a couple, also failed.
```
(compass_env) griffink2@awld3094kg COMPASS % conda install conda-forge::llvm-openmp
Channels:
 - defaults
 - conda-forge
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package llvm-openmp-18.1.6-hde57baf_0 is excluded by strict repo priority
```

**Comment by RaphaelHablesreiter** [comment]
You are still using osx-arm64 as a platform, which means that you use the arm/m-processor as a platform. Many packages are not available here. Try to install conda and brew for x86_64.

**Comment by kjpg** [comment]
this is getting way too deep in the weeds for ltd CLI skills. In my experience with these packages, not a single install has ever been as simple as the readme.md 3-line execution wonder claims.  as for arm64, I am just allowing installs to do their defaults. I am on an M2 mac, btw.  quick look at anaconda and i don't see an llvm installer specifying x86-64. MissionBio has COMPASS as part of Mosaic now, so I think I'll let that do it's thing and see the results. Thanks for your inputs. 
Christine.

**Comment by e-sollier** [comment]
Hopefully you can get COMPASS to work through Moisaic.
Otherwise, I've just made a version of COMPASS which does not require OpenMP, in the new branch: https://github.com/cbg-ethz/COMPASS/tree/no_OMP . You can download the code from https://github.com/cbg-ethz/COMPASS/archive/refs/heads/no_OMP.zip (you may still need to change the compiler in the makefile). This version is slower, but should hopefully be easier to compile if openMP is an  issue.

**Comment by andreyurch** [comment]
> Hopefully you can get COMPASS to work through Moisaic. Otherwise, I've just made a version of COMPASS which does not require OpenMP, in the new branch: https://github.com/cbg-ethz/COMPASS/tree/no_OMP . You can download the code from https://github.com/cbg-ethz/COMPASS/archive/refs/heads/no_OMP.zip (you may still need to change the compiler in the makefile). This version is slower, but should hopefully be easier to compile if openMP is an issue.

Actually only this variant worked for me!  Thank you very much!!!
