### ISSUE TITLE
compass installation

### ISSUE THREAD

**Issue by kjpg** [cbg-ethz/COMPASS#19]
Hi, 

I am trying run COMPASS on some mouse data.  I was using the MOSAIC package, but the way they have integrated COMPASS only works with human samples (it ran with one of their tutorial data but it tries to annotate my mouse data and fails).

I have tried installing COMPASS independently but just get errors from the get go.  git install and cd to compass but 'make' fails. I went ahead and tried to run COMPASS anyway but that fails ("zsh: no such file or directory: ./COMPASS").  

using M1 macOS sonoma

thanks, kevin

<img width="744" alt="image" src="https://github.com/user-attachments/assets/15eb5e02-a29a-408a-99fb-b40c6da30205">

**Comment by e-sollier** [comment]
Hi,

sorry to hear that you are having trouble installing COMPASS. Did you try the fix suggested in https://github.com/cbg-ethz/COMPASS/issues/15?

I made a version of COMPASS which does not use openMP. It is slower but should not have these installation issues on macOS. You can download it from https://github.com/cbg-ethz/COMPASS/archive/refs/heads/no_OMP.zip (unzip it, cd into the directory and run `make`).
