### ISSUE TITLE
Can you expose more parameters?

### ISSUE THREAD

**Issue by murphycj** [cbg-ethz/COMPASS#9]
Hello, can you expose the parameters to control the ADO rate and cell doublet rate? Do you think that is worthwhile?

**Comment by e-sollier** [comment]
Hi,
I have just exposed more parameters, including --dropoutrate and --doubletrate and a few others described in the readme. Hopefully this is helpful for you, although I think that these parameters do not need to be changed in most cases.

**Comment by murphycj** [comment]
Thanks!
